// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateSongs(ctx context.Context, arg CreateSongsParams) (Song, error)
}

var _ Querier = (*Queries)(nil)
