// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: songs.sql

package db

import (
	"context"
)

const createSongs = `-- name: CreateSongs :one
INSERT INTO songs (
"group",
"name",
"releaseDate",
"text",
"link"
) VALUES (
 $1,$2,$3,$4,$5
) RETURNING id, "group", name, "releaseDate", text, link
`

type CreateSongsParams struct {
	Group       string `json:"group"`
	Name        string `json:"name"`
	ReleaseDate string `json:"releaseDate"`
	Text        string `json:"text"`
	Link        string `json:"link"`
}

func (q *Queries) CreateSongs(ctx context.Context, arg CreateSongsParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSongs,
		arg.Group,
		arg.Name,
		arg.ReleaseDate,
		arg.Text,
		arg.Link,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Group,
		&i.Name,
		&i.ReleaseDate,
		&i.Text,
		&i.Link,
	)
	return i, err
}
